### ISSUE TITLE
more complex animation

### ISSUE THREAD

**Issue by winner106** [remotion-dev/d3-example#1]
Thank you very much for your guidance. I tried for a day today, but still failed to achieve it. I made a more complex animation using many years of data, I look forward to your more guidance. Thank you very much!

**Comment by JonnyBurger** [comment]
Hey @winner106,

the reason it does not work is because the animation you are triggering is not declarative.
All animations should be driven by `useCurrentFrame()`, so you need to refactor the code to animate the properties such as width, color, etc. based on useCurrentFrame()!

On why it works this way, we wrote an article that should explain the design decision well: https://remotion.dev/docs/flickering
